### ISSUE TITLE
PyMC -> emcee migration

### ISSUE THREAD

**Issue by mchristoffersen** [uafgeotools/vmod#10]
Moving the MCMC routines over from PyMC to emcee would simplify installation - no need to use conda to install an old PyMC version from conda-forge.

What sort of validation of emcee output/setup is necessary to be confident in the correctness?

**Comment by mfangaritav** [comment]
I think running the notebooks that we have in the repo and getting similar outputs should be enough

**Comment by mfangaritav** [comment]
Ok, I'm gonna close this issue as I migrated VMOD to emcee in 2c323b4f0ffe31de9ebe4d80120ac6990f09fd76 including the notebooks that we have as examples. However, I left the function that uses pymc just in case.
