### ISSUE TITLE
Source parameter checking

### ISSUE THREAD

**Issue by mchristoffersen** [uafgeotools/vmod#8]
Running a Nishimura model with a negative conduit radius gives the same result as the same conduit radius but positive instead of throwing an error or doing something else to signify that it has been given a bad value.

In general I think more input checking in the forward models would be useful. But how to do it?

I often use a block of these at the beginning of a function:

if(condition):
    raise ValueError("error text")

(or TypeError as appropriate). But I'm not sure if that kind of behavior is desired since an inversion routine exploring the parameter space in an automated way might feed a function bad parameters, and if the error is not handled the whole inversion dies.

Maybe better to return nans when given bad parameters, I think this is already the case for some functions/bad parameters.

Could implement as a method in each source model that takes a parameter vector and implements the desired behavior (raise exception or return nans is the parameter set is bad), then call that method anywhere a parameter vector is used.

**Comment by mfangaritav** [comment]
Yes, for the Okada model or the Yang model it verifies some of the parameters and if they are not real it return nans

**Comment by mfangaritav** [comment]
Ok so for this I changed VMOD in 2c323b4f0ffe31de9ebe4d80120ac6990f09fd76 so it returns big numbers instead nans when we have negative depths or radiuses (not all models have these parameters so I did the changes for some specific models).
